### ISSUE TITLE
Commenting upgrade still broken

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-Commenting#34]
See http://omeka.org/forums-legacy/topic/commenting-plugin-throwing-zend_db_statement_mysqli_exception

and

https://forum.omeka.org/t/unknown-column-record-id-in-field-list-when-posting-comments/1543

But, it seems that the record_id column has always existed in this plugin, so I'm not super clear on where this is coming from... another plugin with a conflicting table? Some version of this pre version control? A rogue upgrade from earlier that deleted the column?

**Comment by zerocrates** [comment]
Also:

http://omeka.org/forums-legacy/topic/possible-to-run-commenting-plugin-without-recaptcha#post-115791
http://omeka.org/forums-legacy/topic/commenting-plugin-error-on-show-page
https://groups.google.com/d/msg/omeka-dev/tEhhkBmAlQo/IEHw2RAyAC0J

**Comment by patrickmj** [comment]
`record_id` has been in it since version 1.0, and since it's pretty much at the heart of how it all works, I can't imagine that there's a rogue upgrade that would delete it. Commits that mention the upgrade don't touch it. I've never been able to reproduce this in response to those issues. My best guess is a conflicting plugin somewhere?

**Comment by zerocrates** [comment]
I think the outside-developed Comments plugin uses the same table name. That's probably the source of these complaints, combined with the fact that that plugin doesn't remove its table when it's uninstalled.

**Comment by zerocrates** [comment]
Since people aren't getting errors on install, I suppose you're using CREATE TABLE IF NOT EXISTS. You could either throw an error on install if you already see "your own" table, or you could start off instead by DROP TABLE IF EXISTS-ing it (as that's what we end up telling people to do anyway by uninstalling the plugin).

**Comment by patrickmj** [comment]
That makes sense. I'll probably go for the DROP options
