### ISSUE TITLE
Test new tinymce

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Commenting#42]
Related to https://github.com/omeka/Omeka/issues/837

Commenting, on branch tinymce4, is ready for a look. Since changes are all on the public side, looking at different themes will be important, as will a quick check of doing replies and flagging (though there's no real code change there)

**Comment by mebrett** [comment]
Do themes need to be updated?

**Comment by patrickmj** [comment]
Probably a good idea, at least the bundled themes. Not sure what the status for those is for the release.

**Comment by zerocrates** [comment]
My guess would be there'll be some styling issues... the default styles for buttons tend to need overrides for things like margin and background for the tinymce toolbar.

**Comment by zerocrates** [comment]
There also shouldn't be any theme changes specifically related to this. Updating them is fine but shouldn't be necessary.

**Comment by mebrett** [comment]
Why do we say what’s allowed when we also have a formatting toolbar? Commenting will strip not-allowed tags inserted by TinyMCE (heading formatting, for example)

Seasons
	⁃	Spring: contrast is a little hard to read
	⁃	Summer: buttons are fine.
	⁃	Autumn: *very* hard to read!
	⁃	Winter: very hard to read
	⁃	Night: hard to read

Look and work fine:
	•	Santa Fe
	•	Center Row
	•	Rhythm
	•	Minimalist
	•	Berlin
	•	The Daily
	•	Emiglio
	•	Thanks Roy

Commenting just looks weird in general in Big Picture (gets smooshed into the right hand drawer). But the formatting looks fine, if a little too wide for the drawer (on my computer)

**Comment by patrickmj** [comment]
The list of allowed tags is helpful for when people use the source code option, so I'd say I should double-check it's still accurate, but generally keep the list there.

UGH. Yeah. We'll need a good pile of CSS overrides to deal with the themes! Thanks!

**Comment by patrickmj** [comment]
@kimisgold I think I'll need your guidance about why Seasons doesn't play nicely with the new tinyMCE, as Megan describes above. Looks like we've moved on to latest master of core Omeka, but still tinymce4 branch of Commenting.

**Comment by alyssafahringer** [comment]
When testing Rhythm on Safari, the text of my comment overlaps with the user icon, and Reply is situated oddly on the page. [link to item view](http://dev.omeka.org/afahring/Omeka/items/show/116#comment-4) 

![screen shot 2018-01-30 at 11 18 14 am](https://user-images.githubusercontent.com/8807816/35577374-60c42e04-05af-11e8-9f20-5a4fcc880ca8.png)

**Comment by alyssafahringer** [comment]
Testing minimalist, and reply is situated oddly again: [link to item view](http://dev.omeka.org/afahring/Omeka/items/show/109#comment-5)
![screen shot 2018-01-30 at 11 29 20 am](https://user-images.githubusercontent.com/8807816/35578068-1344f1fc-05b1-11e8-91cc-dd1d2659b42f.png)

**Comment by alyssafahringer** [comment]
Same issue with Berlin: [link](http://dev.omeka.org/afahring/Omeka/items/show/100#comment-6)

**Comment by patrickmj** [comment]
It looks like the placement of the Reply button has been consistently there for quite a while. Rhythm's issues also look like they've been present for a while.

**Comment by patrickmj** [comment]
@mebrett Updates to Seasons master branch and latest Commenting tinymce4 branch should address the issues you saw with the buttons

**Comment by mebrett** [comment]
Updates to seasons has resolved the issues for me (on Safari, Firefox, and Chrome)

**Comment by patrickmj** [comment]
@alyssafahringer recent changes to tinymce4 branch of Commenting should fix the issue of overlap in Rhythm (no need to update the theme)

**Comment by alyssafahringer** [comment]
It doesn't seem to have fixed it on my install for some reason? I did go in and update the plugin after first trying without the update.

**Comment by mebrett** [comment]
I had to do a hard refresh to get the changes to show.

**Comment by alyssafahringer** [comment]
Rhythm looks good now. (Took a few hard refreshes.)
