### ISSUE TITLE
Unable to make comments

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-Commenting#43]
On branch tinymce4. Public commenting is disabled, no Akismet key. Captcha is (afaik) set up properly. 

When I try to leave a comment, logged in as admin, I keep getting the message `Value is required and can't be empty`.

In my logs, I'm seeing 

```
2017-10-11T16:16:40-04:00 ERR (3): exception 'Zend_Controller_Action_Exception' with message 'Context "dc-rdf" does not exist' in /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Action/Helper/ContextSwitch.php:532
Stack trace:
#0 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Action/Helper/ContextSwitch.php(1239): Zend_Controller_Action_Helper_ContextSwitch->hasContext('dc-rdf', true)
#1 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Action/Helper/ContextSwitch.php(257): Zend_Controller_Action_Helper_ContextSwitch->hasActionContext('browse', 'dc-rdf')
#2 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Omeka/Controller/AbstractActionController.php(475): Zend_Controller_Action_Helper_ContextSwitch->initContext()
#3 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Omeka/Controller/AbstractActionController.php(72): Omeka_Controller_AbstractActionController->_setActionContexts()
#4 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(281): Omeka_Controller_AbstractActionController->__construct(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http), Array)
#5 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#8 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#9 /websites/omekadev/home/www/mebrett/Omeka/index.php(23): Omeka_Application->run()
#10 {main}
```

**Comment by patrickmj** [comment]
Huh. I'm seeing that now too. Don't know what might've changed, but am digging in.

**Comment by patrickmj** [comment]
That error log doesn't seem relevant, as it's from 2017.

The big question that I haven't been able to sort out is the difference this line makes: https://github.com/omeka/plugin-Commenting/blob/1eacfbe339ee0f77b801eacedc7dd24b70333e63/views/public/javascripts/commenting.js#L82

Calling the `Omeka.wysiwig()` function makes it look the same as the admin side. But, with that called, the submission has the problem with validation that both Megan and I are seeing. If I comment that out, data is submitted and validated without a problem.

Any thoughts @zerocrates ?

**Comment by zerocrates** [comment]
I believe you want to do this: remove the _following_ line that manually adds the editor, but leave the wysiwyg line in.

You're already setting up the editor on the comment body textarea with the `selector` in your wysiwyg function, so there's no point to add it again right after, and it's probably causing some sort of conflict.

**Comment by patrickmj** [comment]
huh. looks like that's a quick and easy fix. thanks!
