### ISSUE TITLE
Test new email notifications and other PRs

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Commenting#47]
The big new feature here is more email notifications when a comment is submitted, to it calls for multiple people submitting comments, and most importantly multiple people in the new configuration for who receives email notifications.

There are also some smaller changes in the PRs regarding sorting comments, and updating some javascript. They look pretty small and reasonable, but always good to keep an eye on any new oddities.

**Comment by luku** [comment]
I actually found one bug in notification job. For author name it's using `html_escape()` function, but it does nothing in background job. Would you prefer to run htmlspecialchars() directly, or rather adding logic for cli mode in globals.php?

**Comment by patrickmj** [comment]
Interesting question. The recent flurry of activity with PRs and commits to Omeka Classic is related to a planned new release very soon, so this gets at some deep, quick decisions. Calling in @zerocrates for thoughts on core vs plugin changes.

**Comment by mebrett** [comment]
@patrickmj Which branch of Commenting?

**Comment by patrickmj** [comment]
master should now have everything from pull requests, and updates for new tinymce4, so go with master

**Comment by zerocrates** [comment]
@patrickmj @luku I'll think this over a bit... There's some historical reasons, as the helpers used to not be available outside of the views proper.

Probably the straightforward fix if we were going to fix this in the core would be to move the hook/filter definitions out of the global custom.php and into the initialization of the plugin broker. That's probably a good idea just generally but I'm not sure I want to try to push it into this release.

**Comment by zerocrates** [comment]
Direct use of htmlescape is probably the way to go here for the time being.
