### ISSUE TITLE
Handling of user-entered urls

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-Commenting#49]
Per a [post on the forum](https://forum.omeka.org/t/commenting-plugin-new-comment-notification-emails/11057/3?u=mebrett), there can be interest results if someone gives their website when leaving a comment, the rendering of that comment on the admin side can be werid.

Example - I left a comment and entered `www.google.com` as the website. If I click on the Name (rendered as a link) in the admin side, I get the following error:

```
Zend_Controller_Action_Exception: Action "wwwGoogleCom" does not exist and was not trapped in __call() in /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Action.php:485
Stack trace:
#0 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('wwwGoogleComAct...', Array)
#1 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('wwwGoogleComAct...')
#2 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /var/www/html/mebrett/Omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#4 /var/www/html/mebrett/Omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#5 /var/www/html/mebrett/Omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#6 /var/www/html/mebrett/Omeka/admin/index.php(28): Omeka_Application->run()
#7 {main}
````

**Comment by zerocrates** [comment]
I'm assuming this is equally a problem on the frontend?

It's a standard problem of not ensuring the URL as output is absolute, but it's probably the same front and back.

**Comment by mebrett** [comment]
Yes, same issue front and back - ex http://dev.omeka.org/mebrett/Omeka/items/show/3643
Can we change the plugin so that it only accepts absolute urls?

**Comment by zerocrates** [comment]
We could but that wouldn't affect existing comments.

We can do what we do in a couple other places, stick on the http:// if it seems like the URL doesn't have a scheme on it.

**Comment by zerocrates** [comment]
This should be fixed, along with a couple other fairly significant issues with the handling of these author values.

**Comment by mebrett** [comment]
That did. Thanks
