### ISSUE TITLE
Testing for commenting updates

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-Commenting#50]
The master branch includes many changes to how comments are submitted and rendered, so that needs a general once-over. Changes to notice there are the reduced number of choices on the TinyMCE toolbar, and a generally more restrictive set of allowed HTML (pretty much only the things that are shown in the list are allowed, where there were more options previously that weren't listed).

The "non-absolute website field" thing should have been tested enough already.

The admin UI is significantly changed to move things around and include some more information (comment dates), as well as just to fix some bugs with the batch selection (select/unselect all would only work once per page load).

**Comment by mebrett** [comment]
When I try to submit a comment from the pubic interface, I get the following errors:

Logged in
```
Notice: Undefined index: id in /var/www/html/mebrett/Omeka/plugins/Commenting/CommentForm.php on line 84

Fatal error: Uncaught Error: Class 'HTMLPurifier_Config' not found in /var/www/html/mebrett/Omeka/plugins/Commenting/controllers/CommentController.php:242 Stack trace: #0 /var/www/html/mebrett/Omeka/plugins/Commenting/controllers/CommentController.php(71): Commenting_CommentController->_getHtmlPurifier() #1 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Action.php(516): Commenting_CommentController->addAction() #2 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction') #3 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #4 /var/www/html/mebrett/Omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch() #5 /var/www/html/mebrett/Omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap in /var/www/html/mebrett/Omeka/plugins/Commenting/controllers/CommentController.php on line 242
```


Not logged in:
```
Notice: Undefined index: id in /var/www/html/mebrett/Omeka/plugins/Commenting/CommentForm.php on line 84

Notice: Trying to get property 'role' of non-object in /var/www/html/mebrett/Omeka/plugins/Commenting/controllers/CommentController.php on line 60

Fatal error: Uncaught Error: Class 'HTMLPurifier_Config' not found in /var/www/html/mebrett/Omeka/plugins/Commenting/controllers/CommentController.php:242 Stack trace: #0 /var/www/html/mebrett/Omeka/plugins/Commenting/controllers/CommentController.php(71): Commenting_CommentController->_getHtmlPurifier() #1 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Action.php(516): Commenting_CommentController->addAction() #2 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction') #3 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #4 /var/www/html/mebrett/Omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch() #5 /var/www/html/mebrett/Omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap in /var/www/html/mebrett/Omeka/plugins/Commenting/controllers/CommentController.php on line 242
```

**Comment by zerocrates** [comment]
OK the fatal error and the "role" notice should be gone. I'll have to look into the "id" notice a little more.

**Comment by mebrett** [comment]
I'm not able to leave comments both as a logged in and not-logged-in user.

Aesthetic/ux thing on the admin interface - would it be possible to have a line break or something between comments. The icons and approve/flag buttons are far to the left of the comment (all of my comments are short) and it could be hard to track if there were lots of comments. 
<img width="1006" alt="CommentingInterface" src="https://user-images.githubusercontent.com/2314070/82600924-b1d50880-9b7c-11ea-932b-3d5c4c51f78f.png">

**Comment by zerocrates** [comment]
Is that supposed to be "not" or "now"?

**Comment by mebrett** [comment]
Now. I'll fix it.

**Comment by zerocrates** [comment]
Okay, there's now a subtle horizontal divider between comments on the admin.

I also fixed the "id" notice (it's still happening even though you're probably not seeing it anymore)... that involved some changes to how the form works, so please loop back over to double-check that submission is still OK.

**Comment by mebrett** [comment]
Able to leave comments logged in and not logged in, from Firefox, Safari and Chrome. I like the subtle divider, thanks.
