### ISSUE TITLE
Buttons overlap

### ISSUE THREAD

**Issue by kalbers** [omeka/plugin-Commenting#54]
![132870341-f4728601-4ca3-4ced-9a23-989e0af2bbe5](https://user-images.githubusercontent.com/371262/134528695-5b1e1643-0f2d-48ed-8cde-05ff49966bd6.png)

Can't see the highlighting on buttons when it is clicked. Changing margin-right from 0 to 2 seems to be one solution.

**Comment by kimisgold** [comment]
@kalbers Just pushed a fix, could you see if it works for you?
